[package]
name = "tui"
version = "0.1.0"
edition = "2021"

[dependencies]
serial-keel = { path = "../core" }

tui = "0.19"
crossterm = { version = "0.25" }

tokio = { version = "1" }
enum-iterator = "1.2.0"

chrono = { version = "0.4", features = ["serde"] }
