on:
  push:
    branches:
      - main
  pull_request:

name: Serial Keel - CI

jobs:
  build_and_test_win_macos:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: cargo build
        run: cargo build --bin serial-keel --all-features
      - name: cargo test
        run: cargo test --all-features

  build_and_test_unix:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev
      - name: cargo build
        run: cargo build --bin serial-keel --all-features
      - name: cargo test
        run: cargo test --all-features

  clippy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev
      - name: clippy
        run: cargo clippy --bin serial-keel --all-features

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      RUSTDOCFLAGS: '-D warnings'
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev
      - name: cargo doc
        run: cargo doc --all-features

  python_lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./py"
