on:
  push:
    branches:
      - main
      - sk_continuous_integration
  pull_request:

name: Continuous integration - Serial Keel

jobs:
  checks:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: cargo build
        run: cargo build --bin serial-keel
      - name: cargo test
        run: cargo test

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: cargo doc
        run: cargo doc --no-deps
